## MACHINE LEARNING NOVEMBER MINOR PROJECT 

#### PROBLEM STATEMENT : Create a classification model to predict whether price range of mobile based on certain specifications

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

In [2]:
df = pd.read_csv('mobile_price_range_data.csv')
df.head(10)


battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   
5           1859     0          0.5         1   3       0          22    0.7   
6           1821     0          1.7         0   4       1          10    0.8   
7           1954     0          0.5         1   0       0          24    0.8   
8           1445     1          0.5         0   0       0          53    0.7   
9            509     1          0.6         1   2       1           9    0.1   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   
5        164        1  ...       1004      1654  1067    17     1         10   
6        139        8  ...        381      1018  3220    13     8         18   
7        187        4  ...        512      1149   700    16     3          5   
8        174        7  ...        386       836  1099    17     1         20   
9         93        5  ...       1137      1224   513    19    10         12   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  
5        1             0     0            1  
6        1             0     1            3  
7        1             1     1            0  
8        1             0     0            0  
9        1             0     0            0  

[10 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [4]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

## splitting the data into independent and dependent data 

In [5]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [6]:
X

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7   
1       0.7        136        3   6        905      1988  2631    17     3   
2       0.9        145        5   6       1263      1716  2603    11     2   
3       0.8        131        6   9       1216      1786  2769    16     8   
4       0.6        141        2  14       1208      1212  1411     8     2   
...     ...        ...      ...  ..        ...       ...   ...   ...   ...   
1995    0.8        106        6  14       1222      1890   668    13     4   
1996    0.2        187        4   3        915      1965  2032    11    10   
1997    0.7        108        8   3        868      1632  3057     9     1   
1998    0.1        145        5   5        336       670   869    18    10   
1999    0.9        168        6  16        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  
0            19        0             0     1  
1             7        1             1     0  
2             9        1             1     0  
3            11        1             0     0  
4            15        1             1     0  
...         ...      ...           ...   ...  
1995         19        1             1     0  
1996         16        1             1     1  
1997          5        1             1     0  
1998         19        1             1     1  
1999          2        1             1     1  

[2000 rows x 20 columns]

In [7]:
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

## train test split

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Logistic regression  

In [9]:
from sklearn.linear_model import LogisticRegression
##cross validation
LogRegression=LogisticRegression()
LogRegression.fit(X_train,y_train)


C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [10]:
y_pred = LogRegression.predict(X_test)
y_pred

array([0, 2, 0, 3, 1, 2, 2, 0, 3, 3, 0, 1, 2, 3, 3, 2, 2, 2, 1, 0, 0, 1,
       0, 2, 1, 1, 3, 3, 3, 0, 1, 0, 3, 0, 2, 3, 2, 1, 3, 0, 1, 2, 3, 0,
       3, 3, 3, 1, 3, 1, 3, 2, 0, 0, 2, 0, 1, 2, 0, 0, 1, 3, 2, 2, 2, 0,
       3, 3, 1, 1, 2, 2, 0, 1, 2, 0, 0, 3, 2, 2, 3, 2, 1, 0, 1, 3, 3, 3,
       3, 0, 3, 3, 3, 0, 3, 2, 3, 3, 2, 1, 0, 1, 0, 0, 0, 3, 3, 0, 0, 1,
       0, 0, 3, 3, 2, 1, 3, 3, 0, 2, 1, 3, 2, 1, 3, 3, 0, 3, 0, 2, 3, 0,
       2, 2, 0, 2, 1, 1, 0, 2, 3, 1, 3, 3, 0, 0, 1, 2, 1, 2, 3, 1, 1, 0,
       2, 3, 0, 1, 0, 1, 3, 3, 2, 2, 1, 0, 0, 2, 1, 3, 3, 1, 0, 0, 3, 1,
       1, 2, 0, 1, 0, 0, 0, 1, 3, 2, 0, 2, 0, 0, 0, 0, 1, 3, 3, 1, 0, 1,
       1, 1, 1, 2, 1, 2, 3, 3, 1, 3, 0, 1, 1, 1, 1, 1, 3, 2, 1, 3, 1, 1,
       3, 2, 3, 0, 0, 2, 0, 2, 0, 0, 1, 0, 2, 3, 2, 1, 0, 2, 3, 1, 3, 3,
       2, 3, 0, 3, 2, 2, 2, 3, 3, 1, 1, 3, 2, 1, 2, 3, 3, 3, 3, 0, 2, 2,
       2, 2, 3, 0, 3, 3, 2, 2, 2, 0, 1, 3, 0, 2, 3, 1, 3, 1, 1, 3, 0, 3,
       0, 0, 3, 0, 1, 2, 3, 2, 2, 0, 0, 0, 0, 3, 3,

## Evaluating the Model  

In [11]:
from sklearn.metrics import r2_score
score=r2_score(y_pred,y_test)
score

0.6609143961906125

## Evaluating the model by using cross validation method(best accuracy) 

In [12]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(LogRegression,X_train,y_train,cv=10)
score

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.68656716, 0.6119403 , 0.6119403 , 0.67910448, 0.67910448,
       0.56716418, 0.56716418, 0.64179104, 0.57462687, 0.6119403 ])

In [13]:
np.mean(score)

0.623134328358209

## Confusion matrix 

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[131,  37,   1,   0],
       [ 33,  82,  36,  11],
       [  1,  34,  85,  42],
       [  0,   3,  41, 123]], dtype=int64)

## Testing the Model 

In [15]:
print(LogRegression.predict([[882,1,2.3,1,0,1,7,0.6,197,2,2,20,1058,2556,9,7,19,0,0,1]]))

[1]


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


# KNN CLASSIFICATION

In [16]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [17]:
y_pred1 = neigh.predict(X_test)
y_pred1

array([0, 2, 1, 3, 1, 1, 2, 0, 3, 1, 0, 1, 2, 3, 2, 2, 3, 3, 1, 0, 0, 1,
       1, 2, 0, 1, 3, 2, 2, 0, 0, 0, 3, 0, 1, 1, 2, 0, 3, 0, 2, 2, 2, 0,
       2, 2, 2, 1, 3, 1, 3, 1, 0, 0, 0, 0, 1, 3, 0, 0, 0, 3, 3, 1, 0, 0,
       3, 3, 1, 2, 2, 2, 0, 1, 2, 0, 0, 3, 2, 2, 3, 2, 1, 0, 1, 3, 1, 3,
       3, 0, 3, 3, 2, 1, 3, 2, 2, 3, 1, 1, 0, 0, 1, 0, 0, 3, 2, 0, 1, 1,
       0, 0, 3, 2, 2, 2, 3, 2, 0, 2, 1, 3, 2, 1, 3, 3, 0, 2, 0, 2, 3, 0,
       2, 2, 0, 3, 1, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 1, 2, 3, 1, 1, 0,
       2, 2, 0, 1, 0, 2, 2, 3, 3, 2, 1, 0, 1, 2, 2, 3, 3, 0, 1, 0, 3, 1,
       1, 2, 1, 0, 0, 0, 0, 0, 3, 2, 0, 3, 0, 0, 0, 0, 1, 3, 2, 1, 0, 1,
       1, 1, 1, 1, 2, 2, 3, 3, 1, 2, 0, 0, 0, 2, 1, 1, 3, 1, 0, 2, 1, 1,
       3, 2, 2, 0, 0, 2, 1, 3, 0, 1, 2, 0, 2, 3, 2, 0, 1, 3, 3, 0, 1, 3,
       2, 3, 0, 3, 1, 2, 3, 2, 2, 1, 0, 3, 3, 1, 3, 3, 3, 2, 3, 0, 1, 2,
       2, 1, 3, 0, 1, 3, 2, 2, 2, 0, 0, 1, 0, 2, 3, 1, 3, 1, 0, 3, 1, 2,
       0, 0, 3, 0, 1, 2, 3, 3, 3, 1, 1, 0, 1, 3, 3,

## Evaluating the Model

In [18]:
from sklearn.metrics import r2_score
score=r2_score(y_pred1,y_test)
score

0.9288077530365502

## Evaluating the model by using cross validation method(best accuracy)  

In [19]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(neigh,X_train,y_train,cv=5)
score

array([0.90298507, 0.88432836, 0.93283582, 0.89179104, 0.91044776])

In [20]:
np.mean(score)

0.9044776119402986

## confusion matrix 

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred1)

array([[164,   5,   0,   0],
       [ 10, 149,   3,   0],
       [  0,  19, 140,   3],
       [  0,   0,  18, 149]], dtype=int64)

## Testing the Model

In [22]:
print(neigh.predict([[882,1,2.3,1,1,1,7,0.6,197,2,2,20,1888,3005,9,7,19,1,1,1]]))

[2]


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


##  Decision Tree Classifier

In [23]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [24]:
y_pred2 = clf.predict(X_test)
y_pred2

array([0, 2, 1, 3, 1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 2, 2, 3, 3, 1, 0, 0, 1,
       1, 2, 0, 2, 2, 2, 2, 0, 1, 0, 3, 0, 1, 1, 2, 1, 3, 0, 2, 3, 2, 0,
       3, 2, 1, 1, 3, 1, 3, 1, 0, 0, 0, 0, 1, 3, 0, 0, 1, 3, 3, 1, 0, 0,
       3, 3, 1, 2, 2, 2, 0, 1, 3, 0, 1, 3, 2, 2, 3, 2, 1, 0, 2, 3, 2, 3,
       3, 0, 3, 3, 2, 1, 3, 2, 2, 3, 1, 1, 0, 0, 1, 1, 0, 3, 3, 0, 1, 1,
       0, 0, 2, 1, 2, 2, 2, 3, 0, 2, 1, 3, 2, 1, 3, 3, 1, 3, 0, 2, 3, 0,
       2, 2, 0, 2, 1, 1, 0, 2, 3, 1, 2, 3, 0, 0, 0, 1, 2, 2, 3, 1, 1, 0,
       2, 2, 0, 2, 0, 1, 2, 3, 3, 3, 1, 0, 0, 2, 2, 3, 3, 1, 1, 0, 3, 1,
       2, 2, 1, 0, 0, 0, 0, 0, 3, 2, 0, 3, 0, 0, 0, 0, 1, 3, 2, 2, 0, 1,
       1, 1, 1, 1, 2, 2, 3, 3, 1, 2, 0, 0, 0, 2, 1, 1, 3, 1, 0, 3, 1, 1,
       3, 2, 3, 0, 0, 1, 1, 2, 0, 1, 2, 0, 2, 3, 2, 1, 1, 3, 3, 0, 2, 3,
       3, 3, 0, 3, 1, 2, 3, 3, 2, 1, 1, 3, 3, 0, 3, 3, 3, 3, 3, 1, 1, 2,
       2, 1, 2, 0, 2, 3, 2, 2, 2, 0, 0, 1, 0, 2, 3, 1, 3, 1, 0, 3, 1, 2,
       0, 0, 3, 0, 1, 3, 3, 3, 3, 0, 1, 0, 1, 3, 3,

## Evaluating the model 

In [25]:
from sklearn.metrics import r2_score
score=r2_score(y_pred1,y_test)
score

0.9288077530365502

## Evaluating the model by using cross validation method(best accuracy) 

In [26]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(clf,X_train,y_train,cv=5)
score

array([0.81343284, 0.80223881, 0.79104478, 0.79850746, 0.83955224])

In [27]:
np.mean(score)

0.808955223880597

## Confusion matrix 

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[131,  37,   1,   0],
       [ 33,  82,  36,  11],
       [  1,  34,  85,  42],
       [  0,   3,  41, 123]], dtype=int64)

## SVM Classifier with linear and rbf kernel 

In [29]:
from sklearn import svm
svm = svm.SVC()
svm.fit(X_train,y_train)

SVC()

In [30]:
y_pred3 = svm.predict(X_test)
y_pred3

array([0, 2, 1, 3, 1, 1, 2, 0, 3, 1, 0, 0, 2, 3, 2, 2, 3, 3, 1, 0, 0, 1,
       1, 2, 0, 1, 3, 2, 2, 0, 0, 0, 3, 0, 1, 1, 2, 0, 3, 0, 2, 3, 2, 0,
       2, 2, 2, 1, 3, 1, 3, 1, 0, 0, 1, 1, 1, 3, 0, 0, 1, 3, 3, 1, 0, 0,
       3, 3, 1, 2, 2, 2, 0, 1, 2, 0, 0, 3, 2, 2, 3, 2, 1, 0, 1, 3, 1, 3,
       3, 0, 3, 3, 2, 1, 3, 2, 2, 3, 1, 1, 0, 0, 1, 0, 0, 3, 2, 0, 1, 1,
       0, 0, 3, 1, 3, 2, 3, 2, 0, 2, 1, 3, 2, 1, 3, 3, 0, 3, 0, 2, 3, 0,
       2, 2, 0, 3, 1, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 1, 1, 2, 3, 1, 1, 0,
       2, 2, 0, 1, 0, 2, 2, 3, 3, 2, 1, 0, 1, 2, 2, 3, 3, 0, 1, 0, 3, 1,
       1, 2, 1, 0, 0, 0, 0, 0, 3, 2, 0, 3, 0, 0, 0, 0, 1, 3, 3, 1, 0, 1,
       1, 1, 1, 2, 2, 3, 3, 3, 1, 2, 0, 0, 0, 2, 1, 1, 3, 1, 0, 2, 1, 1,
       3, 2, 3, 0, 0, 2, 1, 3, 0, 1, 2, 0, 2, 3, 2, 0, 1, 3, 3, 0, 1, 3,
       3, 3, 0, 3, 1, 2, 3, 3, 2, 1, 1, 3, 3, 1, 3, 3, 3, 3, 3, 0, 1, 2,
       2, 2, 3, 0, 2, 3, 2, 2, 2, 1, 0, 1, 0, 3, 3, 1, 3, 1, 0, 3, 1, 2,
       0, 0, 3, 0, 1, 2, 3, 3, 3, 1, 1, 0, 1, 3, 3,

## Evaluating the model 

In [31]:
from sklearn.metrics import r2_score
score=r2_score(y_pred1,y_test)
score

0.9288077530365502

## Evaluating the model by using Cross validation method(best accuracy) 

In [32]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(clf,X_train,y_train,cv=5)
score

array([0.80970149, 0.79850746, 0.81716418, 0.79104478, 0.82462687])

In [33]:
np.mean(score)

0.8082089552238806

## Confusion matrix

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred3)

array([[164,   5,   0,   0],
       [  3, 158,   1,   0],
       [  0,   9, 147,   6],
       [  0,   0,   8, 159]], dtype=int64)

#  Random Forest Classifier

In [35]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(max_depth=2, random_state=0)
clf1.fit(X, y)

RandomForestClassifier(max_depth=2, random_state=0)

In [36]:
y_pred4 = clf1.predict(X_test)
y_pred4

array([0, 2, 0, 2, 1, 2, 2, 0, 3, 1, 0, 0, 3, 3, 3, 2, 3, 3, 1, 0, 0, 1,
       0, 1, 0, 1, 3, 3, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 3, 1, 2, 3, 3, 0,
       3, 3, 2, 0, 3, 0, 3, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 3, 2, 2, 0, 0,
       3, 3, 0, 2, 2, 3, 0, 1, 3, 0, 0, 3, 2, 2, 3, 2, 0, 0, 1, 3, 2, 3,
       3, 0, 3, 3, 2, 0, 3, 2, 1, 3, 2, 1, 0, 0, 0, 0, 0, 3, 3, 0, 0, 1,
       0, 0, 3, 1, 3, 3, 3, 3, 0, 2, 0, 3, 3, 1, 3, 3, 0, 2, 0, 3, 3, 0,
       3, 3, 1, 3, 1, 0, 0, 2, 2, 0, 3, 2, 0, 0, 0, 1, 1, 2, 3, 1, 1, 0,
       3, 2, 0, 1, 0, 2, 3, 2, 3, 3, 1, 0, 0, 2, 1, 3, 3, 0, 0, 0, 3, 1,
       1, 2, 0, 0, 0, 0, 0, 0, 3, 3, 0, 3, 0, 0, 0, 0, 1, 3, 3, 1, 0, 0,
       2, 1, 0, 2, 1, 3, 2, 3, 1, 2, 0, 0, 0, 1, 1, 1, 3, 1, 0, 2, 2, 1,
       3, 1, 3, 0, 0, 2, 0, 3, 0, 1, 1, 0, 1, 3, 2, 0, 1, 3, 3, 0, 0, 3,
       2, 3, 0, 3, 0, 3, 3, 3, 2, 1, 0, 3, 3, 1, 3, 3, 3, 3, 3, 0, 1, 2,
       3, 2, 3, 0, 2, 3, 2, 3, 2, 1, 0, 2, 0, 3, 3, 1, 3, 1, 0, 3, 1, 2,
       0, 0, 2, 0, 1, 2, 3, 3, 3, 1, 1, 0, 0, 3, 3,

## Evaluating the model 

In [37]:
from sklearn.metrics import r2_score
score=r2_score(y_pred1,y_test)
score

0.9288077530365502

## Evaluating the model by using cross validation method(best accuracy) 

In [38]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(clf,X_train,y_train,cv=5)
score

array([0.82089552, 0.7761194 , 0.80597015, 0.7761194 , 0.83955224])

In [39]:
np.mean(score)

0.8037313432835822

## Confusion matrix 

In [40]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred4)

array([[166,   3,   0,   0],
       [ 53,  92,  17,   0],
       [  0,  33,  82,  47],
       [  0,   0,   8, 159]], dtype=int64)